name: "Bug Report"
description: "Report a bug in the Arliz repository (LaTeX build, content rendering, or asset issues)."
title: "[BUG] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to report a bug. Please fill out the fields below with as much detail as you can. Remove any placeholder text before submitting.

  - type: input
    id: bug_title
    attributes:
      label: "1. Short Description of the Bug"
      description: "Provide a concise summary (e.g., \"Undefined control sequence in part02.tex\")."
      placeholder: "e.g., \"LaTeX compilation error: Undefined control sequence in Part 2\""
      required: true

  - type: textarea
    id: bug_description
    attributes:
      label: "2. Steps to Reproduce"
      description: |
        List the exact steps needed to reproduce the bug. Include:
        - Which file(s) you edited (e.g., `book/parts/part02/part02.tex`).
        - Commands you ran to compile (e.g., `xelatex Arliz.tex`).
      placeholder: |
        1. Open `book/parts/part02/part02.tex`.  
        2. Add a new theorem environment.  
        3. Run `xelatex book/Arliz.tex`.  
      required: true

  - type: textarea
    id: expected_behavior
    attributes:
      label: "3. Expected Behavior"
      description: "Describe what should have happened (e.g., successful compilation, correct rendering of equation)."
      placeholder: "e.g., \"The new theorem should compile without errors and appear formatted correctly in the PDF.\""
      required: true

  - type: textarea
    id: actual_behavior
    attributes:
      label: "4. Actual Behavior"
      description: "Describe what actually happened, including error messages or incorrect output."
      placeholder: |
        "Compilation failed with the following error:  
        ```  
        ! Undefined control sequence.  
        l.52 \newtheorem{theorem}  
        ```"
      required: true

  - type: textarea
    id: latex_log
    attributes:
      label: "5. LaTeX Compilation Log (if applicable)"
      description: |
        Copy and paste the relevant portion of the `.log` file or console output that shows the error. If the bug is not related to compilation, you may leave this blank.
      placeholder: |
        "  
        This is the excerpt from the `.log`:  
        ```
        ! Undefined control sequence.  
        l.52 \newtheorem{theorem}  
        ```  
        "
      required: false

  - type: textarea
    id: additional_context
    attributes:
      label: "6. Additional Context (Optional)"
      description: |
        Any other information that might help diagnose the issue, such as:
        - Recent changes you made (e.g., added a new package in `config/latex-packages.tex`).
        - A minimal code snippet if the bug is reproducible in isolation.
      placeholder: |
        "  
        I recently updated `config/macros.tex` to define `\newcommand{\Z}{\mathbb{Z}}`, and then inserted it in `book/parts/part02/part02.tex`.  
        "
      required: false
