name: "Bug report"
description: "Report a bug or compilation error in the Arliz repository."
title: "[BUG] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug in **Arliz**. Please fill out the fields below to help us reproduce and fix the issue as efficiently as possible.
  - type: input
    id: os_platform
    attributes:
      label: "Operating System / Platform"
      description: "Specify the OS or platform on which you attempted to compile Arliz (e.g., Ubuntu 22.04, macOS 12.3, Windows 10)."
      placeholder: "e.g., Ubuntu 22.04"
  - type: dropdown
    id: latex_engine
    attributes:
      label: "LaTeX Engine"
      description: "Indicate which LaTeX engine you used to compile the project."
      options:
        - "xelatex"
        - "pdflatex"
        - "lualatex"
        - "latexmk"
  - type: textarea
    id: reproduction_steps
    attributes:
      label: "Steps to Reproduce"
      description: |
        Describe the exact steps you took leading up to the error. For example:
        1. Cloned the repository at commit `abcdef`.
        2. Ran `cd book && xelatex Arliz.tex`.
        3. Observed the following error messages: …
  - type: dropdown
    id: affected_file
    attributes:
      label: "Affected File(s)"
      description: |
        Select the LaTeX file or configuration file where the error occurred. If multiple files are affected, choose one and list others in “Other File(s)”.
      options:
        - "book/Arliz.tex"
        - "book/frontmatter/title.tex"
        - "book/parts/part01/part01.tex"
        - "book/parts/part02/part02.tex"
        - "book/parts/part03/part03.tex"
        - "book/parts/part04/part04.tex"
        - "config/macros.tex"
        - "config/latex-packages.tex"
        - "Other"
  - type: input
    id: other_file
    attributes:
      label: "If “Other”, specify file path"
      description: "Provide the relative path(s) to any additional file(s) involved."
      placeholder: "e.g., book/parts/part05/part05.tex"
  - type: textarea
    id: expected_behavior
    attributes:
      label: "Expected Behavior"
      description: "Describe what you expected to happen (e.g., successful compilation, correct output in PDF)."
  - type: textarea
    id: actual_behavior
    attributes:
      label: "Actual Behavior"
      description: "Describe what actually happened, including any console errors or LaTeX warnings."
  - type: textarea
    id: error_log
    attributes:
      label: "Error Log / Console Output"
      description: "Copy and paste the relevant error messages or console output here. If the log is lengthy, attach a snippet or reference a file under `book/logs/`."
  - type: textarea
    id: additional_context
    attributes:
      label: "Additional Context"
      description: "Provide any other information that might help us diagnose the issue (e.g., custom packages you added, recent changes to `config/`). If this involves images (e.g., missing figures), ensure they are placed in `book/images/` and referenced correctly."

