name: "Documentation update"
description: "Suggest changes or corrections to documentation, LaTeX macros, or configuration files in Arliz."
title: "[DOCS] "
labels: ["documentation"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for helping improve the documentation of **Arliz**. Please complete the fields below with as much detail as possible.
  - type: dropdown
    id: doc_section
    attributes:
      label: "Documentation Section"
      description: "Which documentation area are you updating?"
      options:
        - "Book Content (`book/parts/...`)"
        - "Frontmatter (`book/frontmatter/...`)"
        - "Backmatter (`book/backmatter/...`)"
        - "Configuration (`book/config/...`)"
        - "README"
        - "CONTRIBUTING"
        - "Other"
  - type: input
    id: other_doc_section
    attributes:
      label: "If “Other”, specify file or location"
      description: "Provide the relative path or description for the documentation you wish to update."
      placeholder: "e.g., `book/appendix/glossary.tex`"
  - type: textarea
    id: change_details
    attributes:
      label: "Description of Changes"
      description: "Describe the documentation changes you propose, including any LaTeX commands, macros, or new files."
      placeholder: |
        For example:
        - Corrected the definition of “identifier” in Part 02.
        - Added `\newcommand{\Z}{\mathbb{Z}}` macro and updated examples accordingly.
  - type: textarea
    id: motivation
    attributes:
      label: "Motivation"
      description: "Explain why these documentation changes are necessary or beneficial."
  - type: textarea
    id: additional_context
    attributes:
      label: "Additional Context"
      description: "Provide any other information, references, or sample outputs (e.g., before/after PDF snapshots)."

