name: "Documentation Update"
description: "Request an update or correction to the Arliz documentation (frontmatter, backmatter, README, etc.)."
title: "[DOC] "
labels: ["documentation"]
body:
  - type: markdown
    attributes:
      value: |
        Use this template to request corrections or additions to the documentation. Provide specific details to help reviewers understand the change. Remove placeholder text before submitting.

  - type: input
    id: doc_title
    attributes:
      label: "1. Short Title"
      description: "Summarize the documentation issue or request (e.g., \"Fix typo in README.md\")."
      placeholder: "e.g., \"Update table of contents in frontmatter\""
      required: true

  - type: textarea
    id: doc_location
    attributes:
      label: "2. Documentation Location"
      description: |
        Specify which file(s) need updating (e.g., `book/frontmatter/introduction.tex`, `README.md`).  
        If the issue spans multiple files, list each one.
      placeholder: |
        "  
        - `book/frontmatter/introduction.tex`  
        - `README.md`  
        "
      required: true

  - type: textarea
    id: doc_changes
    attributes:
      label: "3. Description of Change"
      description: |
        Describe what needs to be updated or corrected (e.g., grammar fix, updated citation, missing link, formatting).  
        If suggesting new content, explain the rationale.
      placeholder: |
        "  
        In `book/frontmatter/introduction.tex`, change “Aryleez” to “Arliz” in the title.  
        In `README.md`, add a section on installing required LaTeX packages.  
        "
      required: true

  - type: textarea
    id: additional_context
    attributes:
      label: "4. Additional Context (Optional)"
      description: |
        Any extra information, such as:
        - Link to a rendered PDF where the error appears.  
        - Example of correct formatting or reference style.
      placeholder: |
        "  
        See the PDF at page 5 where the table of contents is misaligned.  
        "
      required: false
