name: Build LaTeX Book

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Install LaTeX
      run: |
        sudo apt-get update
        sudo apt-get install -y texlive-full
    
    - name: Build PDF
      run: |
        cd book
        pdflatex -interaction=nonstopmode Arliz.tex
        biber Arliz || bibtex Arliz || true
        pdflatex -interaction=nonstopmode Arliz.tex
        pdflatex -interaction=nonstopmode Arliz.tex
    
    - name: Check Build
      run: |
        if [ ! -f "book/Arliz.pdf" ]; then
          echo "ERROR: PDF not generated"
          exit 1
        fi
        
        if [ $(stat -c%s "book/Arliz.pdf") -lt 1000 ]; then
          echo "ERROR: PDF too small (likely corrupted)"
          exit 1
        fi
        
        echo "✓ PDF generated successfully"
        echo "Size: $(stat -c%s book/Arliz.pdf) bytes"
    
    - name: Upload PDF
      uses: actions/upload-artifact@v4
      with:
        name: arliz-book
        path: book/Arliz.pdf
    
    - name: Check for Critical Errors
      if: failure()
      run: |
        cd book
        echo "=== Critical Errors ==="
        grep -i "emergency stop\|fatal error\|file.*not found\|undefined control sequence\|no pages of output" Arliz.log || echo "No critical errors in log"
